export enum SYSTEM_ROLES {
    ADMIN = 'Admin',
    MANAGER = 'Manager',
    USER = 'User',
    AUDITOR = 'Auditor',
    SECURITY_OFFICER = 'SecurityOfficer',
}

export const ROLE_HIERARCHY = {
    [SYSTEM_ROLES.ADMIN]: [SYSTEM_ROLES.MANAGER, SYSTEM_ROLES.USER, SYSTEM_ROLES.AUDITOR, SYSTEM_ROLES.SECURITY_OFFICER],
    [SYSTEM_ROLES.MANAGER]: [SYSTEM_ROLES.USER],
    [SYSTEM_ROLES.SECURITY_OFFICER]: [SYSTEM_ROLES.AUDITOR, SYSTEM_ROLES.USER],
    [SYSTEM_ROLES.AUDITOR]: [SYSTEM_ROLES.USER],
    [SYSTEM_ROLES.USER]: [],
};

export const SECURITY_CLEARANCE_LEVELS = {
    PUBLIC: 0,
    CONTROLLED: 1,
    RESTRICTED: 2,
    CONFIDENTIAL: 3,
    SECRET: 4,
    TOP_SECRET: 5,
};
