// AUTO-GENERATED BY scripts/start-tunnels.sh
// Do not edit manually if you are using Cloudflare Tunnels
export const BACKEND_URL = 'https://fees-chassis-commissioner-sticks.trycloudflare.com';
export const API_BASE_URL = `${BACKEND_URL}/api/v1`;
