// AUTO-GENERATED BY scripts/start-tunnels.sh
// Do not edit manually if you are using Cloudflare Tunnels
export const BACKEND_URL = 'https://provide-fioricet-animated-joe.trycloudflare.com';
export const API_BASE_URL = `${BACKEND_URL}/api/v1`;
